spring.datasource.url=jdbc:h2:mem:customer-db
spring.h2.console.enabled=true
customer.service.default.location=Paris
customer.service.default.currency=EUR
customer.service.default.language=French
management.endpoints.web.exposure.include=*
